PATTERNS = <<PATTERNS
{first_name}@{domain}
{last_name}@{domain}
{first_initial}@{domain}
{last_initial}@{domain}
{first_name}{last_name}@{domain}
{first_name}.{last_name}@{domain}
{first_initial}{last_name}@{domain}
{first_initial}.{last_name}@{domain}
{first_name}{last_initial}@{domain}
{first_name}.{last_initial}@{domain}
{first_initial}{last_initial}@{domain}
{first_initial}.{last_initial}@{domain}
{last_name}{first_name}@{domain}
{last_name}.{first_name}@{domain}
{last_name}{first_initial}@{domain}
{last_name}.{first_initial}@{domain}
{last_initial}{first_name}@{domain}
{last_initial}.{first_name}@{domain}
{last_initial}{first_initial}@{domain}
{last_initial}.{first_initial}@{domain}
{first_name}-{last_name}@{domain}
{first_initial}-{last_name}@{domain}
{first_name}-{last_initial}@{domain}
{first_initial}-{last_initial}@{domain}
{last_name}-{first_name}@{domain}
{last_name}-{first_initial}@{domain}
{last_initial}-{first_name}@{domain}
{last_initial}-{first_initial}@{domain}
{first_name}_{last_name}@{domain}
{first_initial}_{last_name}@{domain}
{first_name}_{last_initial}@{domain}
{first_initial}_{last_initial}@{domain}
{last_name}_{first_name}@{domain}
{last_name}_{first_initial}@{domain}
{last_initial}_{first_name}@{domain}
{last_initial}_{first_initial}@{domain}
PATTERNS
